apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - namespace.yaml
  - service-stable.yaml
  - service-canary.yaml
  - rollout.yaml
  - analysis-template.yaml
  - ingress.yaml
