apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-api
spec:
  tls:
    - hosts:
        - java-api.homolog.127.0.0.1.nip.io
      secretName: java-api-tls
  rules:
    - host: java-api.homolog.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-api-stable
                port:
                  number: 8080
