apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/podmonitor.yaml
patches:
  - path: rollout-patch.yaml
  - path: ingress-patch.yaml
  - path: analysis-patch.yaml
