apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-privileged-hostpath.yaml
  - require-run-as-non-root.yaml
  - require-readonly-rootfs.yaml
  - require-resources.yaml
  - disallow-latest-tag.yaml
  - verify-image-signatures.yaml
  - verify-image-attestations.yaml
