apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/disallow-privileged-hostpath.yaml
  - path: patches/require-run-as-non-root.yaml
  - path: patches/require-readonly-rootfs.yaml
  - path: patches/require-resources.yaml
  - path: patches/disallow-latest-tag.yaml
  - path: patches/verify-image-signatures.yaml
  - path: patches/verify-image-attestations.yaml
